### ISSUE TITLE
Reconsider complexity of references to external identifiers?

### ISSUE THREAD

**Issue by clange** [tibonto/aeon#48]
Do we need the complexity of

https://github.com/tibonto/aeon/blob/77a0ce7d192d663a0c0bc83ca149a231af558565/aeon.ttl#L1734

https://github.com/tibonto/aeon/blob/77a0ce7d192d663a0c0bc83ca149a231af558565/aeon.ttl#L1797-L1799

? Wouldn't it suffice to say `... owl:sameAs <https://www.wikidata.org/wiki/Q65929359>`?

Or maybe some AEON-specific subproperty of `owl:sameAs`?

**Comment by StroemPhi** [comment]
@clange: yes, thank you for the hint!

**Comment by StroemPhi** [comment]
I've deleted the data properties for the identifier class (IAO:0020000), as it seems sufficient to just use the IRI of an identifier for any instance of it and then specify things further using `rdfs:comment` or `owl:sameAs`. 
An identifier can also be further specified by asserting its type according to the available subclasses.
![grafik](https://user-images.githubusercontent.com/56996739/126124622-b1aff32a-7759-4b06-b409-eb61292de195.png)

In order to allow a better mapping and to be able to infer the identifier type, there are sub-properties for iao:denotes and also their inverses:
![grafik](https://user-images.githubusercontent.com/56996739/126124884-dfebbf7c-7c70-49ef-99be-f9c18b9ffe35.png)
